Level 2
yahty01/movies-explorer-frontend pull request #1
Opened 2023-10-25 12:30 UTC by yahty01

2023-10-25 13:59 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
У Вас получилась хорошая работа для первого раза. Будет еще 3 итерации для того, чтобы над ней можно было еще поработать и она выгодно смотрелась в Вашем портфолио.
Вносите правки без спешки, следите за тем, что изменилось после внесения той или иной правки в элементе. Убедитесь перед отправкой, что все правки внесены. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут.

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	**Главная**
	- 768 https://yadi.sk/d/l_eCLkz9AeLnTA https://yadi.sk/d/k56xyEh5JNEc3A
	- 320 https://yadi.sk/d/OEZos-ILMRkvVQ https://yadi.sk/d/LK1TwMynWEa_8Q

	**Вход/Регистрация**
	- 1280 https://yadi.sk/i/zBKgaNMNYIw7lQ / 768 https://yadi.sk/d/JP0SfzYZRsqwUA https://yadi.sk/d/exQ57NckSDZ6cQ (сгруппируйте контент по макету, хорошо что подвал прижимается к низу, но здесь это не подвал а панель с кнопками, в макете он больше сгруппирован весь в центре)

	**Фильмы**
	- 768/320  https://yadi.sk/d/2B9b0pvZAcQyAA https://yadi.sk/d/r6gqUAOBDb0zRw

	**Меню**
	- 768/320 https://yadi.sk/d/gcKVGquSlG8Atw

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.

	- Выйти из аккаунта - хорошо бы актуализировать адрес ссылки

- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/c4Ao7wobdVYVKA https://yadi.sk/d/cHSIakS6uq2q2Q (Главная/Фильмы) В проекте есть ошибки БЭМ, воспользуйтесь [валидатором для проверки](https://nglazov.github.io/bem-validator-page/)
	- about-me__personal-github - Название класса должно отражать и обосновывать его же использование. Не следует привязывать именование к внутреннему контенту, т.к. он может легко смениться, используйте смысловой элемент.
	- about-project__timeline-one, about-project__timeline-four, about-project__timeline-one-caption, about-project__timeline-four-caption - то же замечание, что выше, но также обратите внимание, что у одинаковых смысловых элементов следует устанавливать одинаковый клас, для отличий хорошо подходят модификаторы БЭМ.
	- saveButtonClass - используйте булевый модификатор по методологии БЭМ.
	- navigation__burger - одна кнопка имеет два состояния - бургер открыт и бургер закрыт, используйте модификатор БЭМ.
	- navtab__link - аналогичное замечание, одинаковые смысловые элементы имеют один класс, + модификаторы
	- notFound - именование следует скорректировать на кебаб-кейс
	- profile__field-name, profile__name-label, profile__link-edit и т.д. - для одинаковых элементов в профиле используйте одинаковый класс + модификатор

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/i/r3cR1i7uSj3eiA В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи
	- https://yadi.sk/d/ZPgo-dkxsrf-hQ Немного добавьте отступа, чтобы иконка не перекрывала контент
	- https://yadi.sk/i/Mt_emfbsjtk-Qg хорошо бы позиционировать изображение по центру - object-position

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- https://yadi.sk/d/Ztunhfae67K-0g https://yadi.sk/i/wuuqueN_bhKI9w https://yadi.sk/i/g9IHKnS4fBLh7Q (Главная/Вход/Рег/Профиль) Проект содержит ошибки валидации, воспользуйтесь [валидатором для проверки](https://validator.w3.org/#validate_by_input)
	- https://yadi.sk/i/76jsuchgm-c5Cw https://yadi.sk/d/6kxVn2fRC7HPiQ В проекте есть ошибки в консоли
	- Каждый основной контент на странице следует обернуть main, все кроме header и footer (Профиль)
	- В профиле поля следует обернуть формой
	- promo__image - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- notFound - ссылку на странице разместите в поточном режиме

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [ ] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.

	- Форма Авторизации это одинаковый компонент с разным набором полей, хорошо бы его объединить

- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- Для тегов `<form>` следует заполнить атрибут name
	- Добавьте кнопке тип submit, чтобы была проверка полей на валидность

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [ ] <!--1.67--> Растровые и векторные изображения оптимизированы;

	- promo-image.svg - используйте формат png для фоновой картинки

## Количество баллов: 52

## Доп. Комментарии:
	- <html lang="en"> - язык проекта русский

2023-10-28 12:33 UTC, yahty01 commented
1. https://yadi.sk/i/r3cR1i7uSj3eiA Не понятно, что имеется ввиду в данном сриншоте 
2.  Разметка портирована в JSX: не стоит как выпаленное 
3. В проекте есть: не стоит как выполненное

2023-10-28 15:58 UTC, Savallera commented
> 1. https://yadi.sk/i/r3cR1i7uSj3eiA Не понятно, что имеется ввиду в данном сриншоте
> 2. Разметка портирована в JSX: не стоит как выпаленное
> 3. В проекте есть: не стоит как выполненное

Здравствуйте
1. Высоту секции не следует фиксировать, при увеличенном заголовке он выпадает из блока - это отображено на скриншоте и также приложен комментарий после 
2. Это не пункт чек-листа, а сгруппированный блок
3. см. пункт 2

2023-10-28 16:22 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово второе ревью на Ваш проект. Добавился чек по пункту навигации в проекте, над остальными замечаниями следует еще поработать. Чтобы принять проект необходимо минимум 80 баллов. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут. Уверена у Вас все получится!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [ ] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	**Вход/Регистрация**
	- 1280/768 https://yadi.sk/d/wpn2dt1oa22yKQ в проекте https://yadi.sk/d/7bqjoiAJZSviCg в макете  (сгруппируйте контент по макету, хорошо что подвал прижимается к низу, но здесь это не подвал а панель с кнопками, в макете он больше сгруппирован весь в центре)

	**Меню**
	- 768/320 https://yadi.sk/d/gcKVGquSlG8Atw - размер иконки

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/c4Ao7wobdVYVKA https://yadi.sk/d/cHSIakS6uq2q2Q (Главная/Фильмы) В проекте есть ошибки БЭМ, воспользуйтесь [валидатором для проверки](https://nglazov.github.io/bem-validator-page/)
	- about-project__timeline-one, about-project__timeline-four, about-project__timeline-one-caption, about-project__timeline-four-caption - Название класса должно отражать и обосновывать его же использование. Не следует привязывать именование к внутреннему контенту, т.к. он может легко смениться, используйте смысловой элемент., но также обратите внимание, что у одинаковых смысловых элементов следует устанавливать одинаковый клас, для отличий хорошо подходят модификаторы БЭМ.
	- saveButtonClass https://yadi.sk/d/rYSkZmC2jEoMow - используйте булевый модификатор по методологии БЭМ.
	- navigation__burger - одна кнопка имеет два состояния - бургер открыт и бургер закрыт, используйте булевый модификатор БЭМ вместо другого элемента.
	- navtab__link - аналогичное замечание, одинаковые смысловые элементы имеют один класс, + модификаторы
	- notFound - именование следует скорректировать на кебаб-кейс
	- profile__field-name, profile__name-label, profile__link-edit и т.д. - для одинаковых элементов в профиле используйте одинаковый класс + модификатор

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/i/r3cR1i7uSj3eiA В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи
	- https://yadi.sk/d/ZPgo-dkxsrf-hQ Немного добавьте отступа, чтобы иконка не перекрывала контент
	- https://yadi.sk/i/Mt_emfbsjtk-Qg хорошо бы позиционировать изображение по центру - object-position

- [ ] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- https://yadi.sk/d/Ztunhfae67K-0g https://yadi.sk/i/wuuqueN_bhKI9w https://yadi.sk/i/g9IHKnS4fBLh7Q (Главная/Вход/Рег/Профиль) Проект содержит ошибки валидации, воспользуйтесь [валидатором для проверки](https://validator.w3.org/#validate_by_input)
	- https://yadi.sk/i/76jsuchgm-c5Cw https://yadi.sk/d/6kxVn2fRC7HPiQ В проекте есть ошибки в консоли
	- Каждый основной контент на странице следует обернуть main, все кроме header и footer (Профиль)
	- В профиле поля следует обернуть формой
	- promo__image - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/

- [ ] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- notFound - ссылку на странице разместите в поточном режиме

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [ ] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.

	- Форма Авторизации это одинаковый компонент с разным набором полей, хорошо бы его объединить

- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [ ] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- Для тегов `<form>` следует заполнить атрибут name
	- Добавьте кнопке тип submit, чтобы была проверка полей на валидность

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [ ] <!--1.67--> Растровые и векторные изображения оптимизированы;

	- promo-image.svg - используйте формат png для фоновой картинки

## Количество баллов: 61

## Доп. Комментарии:
	- <html lang="en"> - язык проекта русский

2023-10-29 11:33 UTC, Savallera requested changes
# Резюме по работе:

Здравствуйте!
Готово третье ревью на Ваш проект. Добавился чек по соответствию с макетом (небольшой комментарий по поводу высоты кнопики). Баллов еще недостаточно. Обращаю Ваше внимание, что итерация у Вас последняя. Если есть трудности - обращайтесь к наставнику и старшему студенту, они обязательно Вам помогут. Уверена у Вас все получится!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.

	- https://yadi.sk/d/Vn0cT-LMswTXyw можно добавить внутренние отступы для кнопки, для того, чтобы она не ужималась.

- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/c4Ao7wobdVYVKA https://yadi.sk/d/cHSIakS6uq2q2Q (Главная/Фильмы) В проекте есть ошибки БЭМ, воспользуйтесь [валидатором для проверки](https://nglazov.github.io/bem-validator-page/)
	- about-project__timeline-one, about-project__timeline-four, about-project__timeline-one-caption, about-project__timeline-four-caption - Название класса должно отражать и обосновывать его же использование. Не следует привязывать именование к внутреннему контенту, т.к. он может легко смениться, используйте смысловой элемент., но также обратите внимание, что у одинаковых смысловых элементов следует устанавливать одинаковый клас, для отличий хорошо подходят модификаторы БЭМ.
	- saveButtonClass https://yadi.sk/d/rYSkZmC2jEoMow - используйте булевый модификатор по методологии БЭМ вместо active.
	- navtab__link - одинаковые смысловые элементы имеют один класс, + модификаторы
	- notFound - именование следует скорректировать на кебаб-кейс
	- profile__field-name, profile__name-label, profile__link-edit и т.д. - для одинаковых элементов в профиле используйте одинаковый класс + модификатор

- [ ] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.

	- https://yadi.sk/i/R9VzY1KRmA5uBQ В любом месте где есть контент не следует делать фиксацию по высоте, т.к. контент может измениться и это не должно поломать отображение. Если блок содержит фоновое изображение и контент используйте минимальную высоту, Вам следует самостоятельно на примере найти и исправить все похожие случаи
	- https://yadi.sk/d/ZPgo-dkxsrf-hQ https://yadi.sk/d/1Sbn99nIoynJwQ Немного добавьте отступа, чтобы иконка не перекрывала контент

- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.

	- Каждый основной контент на странице следует обернуть main, все кроме header и footer (Профиль)
	- В профиле поля следует обернуть формой
	- promo__image - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/

- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.

	- notFound - ссылку на странице разместите в поточном режиме

- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [x] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [x] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [ ] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.

	- Форма Авторизации это одинаковый компонент с разным набором полей, хорошо бы его объединить

- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.

	- Для тегов `<form>` следует заполнить атрибут name
	- Добавьте кнопке тип submit, чтобы была проверка полей на валидность

- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [ ] <!--1.67--> Растровые и векторные изображения оптимизированы;

	- promo-image.svg - используйте формат png для фоновой картинки

## Количество баллов: 73

## Доп. Комментарии:
	- <html lang="en"> - язык проекта русский

2023-10-30 08:25 UTC, Savallera approved these changes
# Резюме по работе:

Здравствуйте!
У Вас получилась достойная работа. Поздравляю Ваш проект принят, желаю Вам дальнейших успехов во всех начинаниях!

## Верстка и JSX

### Критерии, влияющие на работоспособность
- [x] <!--12--> Все блоки и элементы из макета сверстаны. Размеры и расположение не отличаются от макета на более, чем на 30px на десктопной версии и на 10px на остальных размерах экрана, для которых подготовлен макет. Отличия в размерах не должны визуально противоречить макету и выбиваться из заложенной в макет сетки, в этом случае требуется более строгое соответствие размерам макета.
- [x] <!--10.55--> Проект адаптирован под различные разрешения экрана. Горизонтальный скролл не возникает на разрешениях от 320 пикселей и больше. Нельзя скрывать полосу прокрутки свойством overflow: hidden.
- [x] <!--9.55--> Корректно работает навигация между страницами и ссылки на внешние ресурсы: ни одна ссылка не ведёт в пустоту или на якорь, внешние ссылки открываются в новой вкладке. На все страницы проекта можно попасть, а скрытые блоки можно отобразить.
- [ ] <!--5.55--> Именование классов сделаны по БЭМ.

	- https://yadi.sk/d/c4Ao7wobdVYVKA https://yadi.sk/d/cHSIakS6uq2q2Q (Главная/Фильмы) В проекте есть ошибки БЭМ, воспользуйтесь [валидатором для проверки](https://nglazov.github.io/bem-validator-page/)
	- about-project__timeline-one, about-project__timeline-four, about-project__timeline-one-caption, about-project__timeline-four-caption - Название класса должно отражать и обосновывать его же использование. Не следует привязывать именование к внутреннему контенту, т.к. он может легко смениться, используйте смысловой элемент., но также обратите внимание, что у одинаковых смысловых элементов следует устанавливать одинаковый клас, для отличий хорошо подходят модификаторы БЭМ.
	- saveButtonClass https://yadi.sk/d/rYSkZmC2jEoMow - используйте булевый модификатор по методологии БЭМ вместо active.
	- navtab__link - одинаковые смысловые элементы имеют один класс, + модификаторы
	- notFound - именование следует скорректировать на кебаб-кейс
	- profile__field-name, profile__name-label, profile__link-edit и т.д. - для одинаковых элементов в профиле используйте одинаковый класс + модификатор

- [x] <!--8.55--> Отзывчивая вёрстка, которая корректно тянется на всех промежуточных разрешениях.
- [x] <!--3.38--> В коде используется семантическая разметка: применяются семантические теги, выбор элементов при вёрстке корректен (параграф должен быть параграфом, список — списком); структура DOM-дерева состоит не только из контейнеров div.
- [x] <!--3.38--> Для позиционирования элементов выбран верный подход, описанный корректным синтаксисом.
- [x] <!--3.38--> Каркас макета реализован на Flex layout или Grid layout;
- [x] <!--3.38--> Инфраструктурные файлы проекта созданы через CRA.
- [x] <!--3.38--> Работа модальных окон настроена.
- [ ] Разметка портирована в JSX:
	- [x] <!--3.38--> разметка заключена в ( ), лишние пустые <div> для этого не используются;
	- [x] <!--3.38--> разметка вынесена в соответствующие ей компоненты.
- [ ] В проекте есть:
	- [x] <!--3.38--> директория images/ с картинками,
	- [x] <!--3.38--> директория components/ с JS и CSS-файлами компонентов,
	- [x] <!--3.38--> директория fonts/ со шрифтами.

### Хорошие практики
- [x] <!--2.14--> Кнопки, инпуты и ссылки реализованы во всех состояниях, указанных в макете.
- [ ] <!--2.14--> В макете есть одинаковые элементы. Для их оформления должен быть переиспользован один компонент.

	- Форма Авторизации это одинаковый компонент с разным набором полей, хорошо бы его объединить

- [x] <!--2.14--> Шрифты подключены через @font-face.
- [x] <!--2.14--> Иконки экспортированы в формате SVG.
- [x] <!--2.14--> Элементы формы должны выделяться, когда на них установлен фокус. Состояние фокуса, а также outline стилизованы в соответствии с макетом или на своё усмотрение.
- [x] <!--2.14--> У формы должны быть заданы плейсхолдеры, валидированы обязательные поля.
- [x] <!--2.14--> reset.css запрещен.

### Рекомендации
- [x] <!--1.68--> Для каждого шрифта указаны альтернативные варианты из системных шрифтов.
- [x] <!--1.67--> Для изображений задан атрибут alt с подходящий значением.
- [ ] <!--1.67--> Растровые и векторные изображения оптимизированы;

	- promo-image.svg - используйте формат png для фоновой картинки

## Количество баллов: 91

## Доп. Комментарии:
	- <html lang="en"> - язык проекта русский
	-	promo__image - Хорошей практикой считается отображать декоративные изображения/иконки на псевдоклассах `:before` и `:after` https://habr.com/ru/post/154319/

2023-10-30 12:28 UTC, merged